name: et_drought
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib-base
  - cartopy
  - xarray
  - netcdf4
  - h5netcdf
  - pyarrow
  - beautifulsoup4
  - requests
  - urllib3
  - jupyterlab
  - ipykernel
